version: "2.2"

services: 
  backend:
    image: greggu/uploaddemo-backend:0.1
    container_name: upload-be
    build: 
      context: ./backend
      dockerfile: Dockerfile
    networks: 
      demo:
  frontend:
    image: greggu/uploaddemo-frontend:0.1
    container_name: upload-fe
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "80:80"
    environment: 
      - BACKEND_CLUSTER_IP=upload-be
    networks: 
      demo:
    restart: always

networks:
  demo:
